"""add language to posts

Revision ID: 186316e72045
Revises: 2e57904460e0
Create Date: 2018-11-26 20:09:08.379719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186316e72045'
down_revision = '2e57904460e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
