"""new fields in user model

Revision ID: 606c58411df2
Revises: 150344e10620
Create Date: 2018-11-16 22:50:31.212552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606c58411df2'
down_revision = '150344e10620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
